title: "Georgi Kostov's Portfolio"
description: "A portfolio and blog for Georgi Kostov"
author: "Georgi Kostov"
theme: jekyll-theme-cayman

# Base URL for GitHub Pages
baseurl: "" # Leave this empty if you’re not using a subdirectory
url: "https://georgikostov.github.io"

# Navigation Links
links:
  Home: "/"
  Projects: "/pages/projects/"
  Blog: "/pages/blog/"
  Publications: "/pages/publications/"

# Blog Configuration
collections:
  posts:
    output: true
    permalink: /blog/:title/  # Clean URLs for blog posts

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag       # Adds SEO metadata
  - jekyll-feed          # Generates RSS feed for the blog
  - jekyll-sitemap       # Creates a sitemap for search engines
  - jekyll-paginate      # Enables pagination for blog posts


# Markdown Configuration
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown


# Exclude Unnecessary Files and Directories
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md